import { Chat, ChatMessage } from '@common/interfaces/chat';
import { ActiveGame } from './interfaces/active-game';
import { FriendRequest } from './interfaces/friend-request';
import { Card } from './interfaces/game-card/card';
import { CardCreationOutputDto } from './interfaces/game-card/card-creation.dto';
import { CardFiles } from './interfaces/game-card/card-files';
import { CardPreview } from './interfaces/game-card/card-preview';
import { CardValidationOutputDto } from './interfaces/game-card/card-validation.dto';
import { ChatMessageOutputDto } from './interfaces/game-play/chat-message.dto';
import { GameClickOutputDto } from './interfaces/game-play/game-click.dto';
import { GameConnectionObserverResponseTypeDto, GameConnectionRequestOutputMessageDto } from './interfaces/game-play/game-connection-request.dto';
import { EndgameOutputDto } from './interfaces/game-play/game-endgame.dto';
import { GameValues } from './interfaces/game-play/game-values';
import { Hint } from './interfaces/game-play/hint';
import { GamePlayerConnectionAttemptRemarkFilter } from './interfaces/gateway-dto/game-player-connection-attempt.remark';
import { Notification } from './interfaces/notification';
import { Record } from './interfaces/records/record';
import { User } from './interfaces/user';
export class Event<T> {
    readonly type: T;
    constructor(public readonly name: string) {}
}

export namespace ToServer {
    export const MUTE_USER = 'mute';
    export const UNMUTE_USER = 'unMute';
    export const CLICK = 'send_click';
    export const CHAT_MESSAGE = 'send_chat_message';
    export const PROTOTYPE_CHAT_MESSAGE = 'send_prototype_chat_message';
    export const REQUEST_TO_PLAY = 'request_to_play';
    export const REQUEST_TO_CHAT = 'request_to_chat';
    export const USERNAME_VALIDATION = 'validation';
    export const CARD_VALIDATION_REQUEST = 'send_card_validation_request';
    export const CARD_CREATION_REQUEST = 'send_card_creation_request';
    export const PLAYER_VALIDATION = 'validate_player';
    export const CHEAT = 'get_cheats';
    export const LEAVE_GAME = 'leave_game';
    export const HINT = 'hint';
    export const JOINABLE_GAME_CARDS = 'joinable_game_cards';
    export const SET_GAME_VALUES = 'set_game_values';
    export const GET_GAME_VALUES = 'get_game_values';
    export const ALL_GAME_CARDS = 'all_game_cards';
    export const DELETE_ALL_CARDS = 'delete_all_cards';
    export const DELETE_ALL_RECORDS = 'delete_all_records';
    export const DELETE_CARD = 'delete_card';
    export const GET_ALL_RECORDS = 'get_all_records';
    export const RESET_BEST_TIMES = 'reset_best_times';
    export const IS_PLAYING = 'is_playing';
    export const RESET_ALL_BEST_TIMES = 'reset_all_best_times';
    export const REMOVE_PLAYER = 'remove_player';
    export const CREATE_CHAT = 'create_chat';
    export const LOAD_CHAT = 'load_chat';
    export const SEND_MESSAGE = 'send_message';
    export const REMOVE_CHAT = 'remove_chat';
    export const JOIN_CHAT = 'join_chat';
    export const GET_ALL_CHATS = 'get_all_chats';
    export const FRIEND_REQUEST = 'friend_request';
    export const FRIEND_REQUEST_RESPONSE = 'friend_request_response';
    export const UPDATE_USERNAME = 'update_username';
    export const ACTIVE_GAMES = 'active_games';
    export const JOIN_AS_OBSERVER = 'join_as_observer';
    export const SEND_VOICE_MESSAGE = 'send_voice_message';
    export const KICK_OUT_PLAYER = 'kick_out_player';
    export const TOGGLE_MUTE = 'mute';
    export const RETRIEVE_ALL_ACTIVE_USERS = 'retrieve_all_active_users';
    export const SEND_GAME_SETTINGS = 'send_game_settings';
    export const LEAVE_OBSERVER = 'leave_observer';
}

export namespace FromServer {
    export const MUTE_USER = 'mute';
    export const UNMUTE_USER = 'unMute';
    export const TOGGLE_MUTE = new Event<boolean>('is_mute');
    export const IS_PLAYING = new Event<boolean>('is_playing');
    export const FRONTEND_CARD_TIMES = new Event<Card>('frontend_card_times');
    export const ALL_FRONTEND_CARD_TIMES = new Event<Card[]>('all_frontend_card_times');
    export const GAME_CARD = new Event<CardPreview>('game_card');
    export const SPREAD_HISTORY = new Event<Record>('history_received');
    export const PLAYER_STATUS = new Event<GamePlayerConnectionAttemptRemarkFilter>('player_status');
    export const ENDGAME = new Event<EndgameOutputDto>('endgame');
    export const CLICK_PERSONAL = new Event<GameClickOutputDto>('click_personal');
    export const CLICK_ENEMY = new Event<GameClickOutputDto>('click_enemy');
    export const RESPONSE_TO_JOIN_GAME_REQUEST = new Event<GameConnectionRequestOutputMessageDto>('response_to_play_request');
    export const CARD_VALIDATION = new Event<CardValidationOutputDto>('card_validation');
    export const CARD_CREATION = new Event<CardCreationOutputDto>('card_creation');
    export const CHAT_MESSAGE = new Event<ChatMessageOutputDto>('chat_message');
    export const CHEAT = new Event<string[]>('cheat');
    export const HINT = new Event<Hint>('hint');
    export const DESERTER = new Event<string>('deserter');
    export const VALIDATION_RESPONSE = new Event<boolean>('validation-response');
    export const JOINABLE_GAME_CARDS = new Event<string[]>('joinable_game_cards');
    export const CHEAT_INDEX = new Event<number>('cheat_index');
    export const GAME_VALUES = new Event<GameValues>('game_values');
    export const ALL_GAME_CARDS = new Event<CardPreview[]>('all_game_cards');
    export const CARD_DELETE_RESPONSE = new Event<boolean>('card_delete_response');
    export const GLOBAL_MESSAGE = new Event<string>('global_message');
    export const TIME = new Event<number>('time');
    export const NEXT_CARD = new Event<CardFiles>('next_card');
    export const ALL_RECORDS = new Event<Record[]>('all_records');
    export const RECORD_BEATER = new Event<string>('record_beater');
    export const LOAD_CHAT = new Event<Chat>('load_chat');
    export const NEW_MESSAGE = new Event<ChatMessage>('new_message');
    export const ALL_CHATS = new Event<Chat[]>('all_chats');
    export const ALL_ACTIVE_USERS = new Event<User[]>('all_active_users');
    export const NOTIFICATION = new Event<Notification>('notification');
    export const FRIEND_REQUEST = new Event<FriendRequest>('friend_request');
    export const ACTIVE_GAMES = new Event<ActiveGame[]>('active_games');
    export const JOIN_AS_OBSERVER = new Event<ActiveGame>('join_as_observer');
    export const CHEAT_ALERT = new Event<string>('cheat_alert');
    export const BACK_TO_LOBBY = new Event<string>('back_to_lobby');
    export const RESPONSE_TO_JOIN_GAME_OBSERVER_REQUEST = new Event<GameConnectionObserverResponseTypeDto>('response_to_join_game_observer_request');
    export const NEW_OBSERVER = new Event<string>('new_observer');
    export const OBSERVER_LEFT = new Event<string>('observer_left');
}
